#velocity_joint_mode_controller:
#  type: joint_mode_controller/JointModeController
#  joint_mode: 2 # velocity

velocity_trajectory_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - Actuator1
    - Actuator2
    - Actuator3
    - Actuator4
    - Actuator5
    - Actuator6
    - Actuator7
  gains:
    Actuator1: {p: 3, d: 0, i: 0.2, i_clamp: 2.0}
    Actuator2: {p: 2, d: 0, i: 0.2, i_clamp: 2.0}
    Actuator3: {p: 2, d: 0, i: 0.2, i_clamp: 2.0}
    Actuator4: {p: 3, d: 0, i: 0.2, i_clamp: 2.0}
    Actuator5: {p: 2, d: 0, i: 0.2, i_clamp: 2.0}
    Actuator6: {p: 2, d: 0, i: 0.2, i_clamp: 2.0}
    Actuator7: {p: 2, d: 0, i: 0.2, i_clamp: 2.0}

  velocity_ff:
    Actuator1: 0
    Actuator2: 0
    Actuator3: 0
    Actuator4: 0
    Actuator5: 0
    Actuator6: 0
    Actuator7: 0

  constraints:
    stopped_velocity_tolerance: 0.02
    goal_time: 5.0
    Actuator1:
      goal: 0.007
      trajectory: 0.1
    Actuator2:
      goal: 0.007
      trajectory: 0.1
    Actuator3:
      goal: 0.007
      trajectory: 0.1
    Actuator4:
      goal: 0.007
      trajectory: 0.1
    Actuator5:
      goal: 0.007
      trajectory: 0.1
    Actuator6:
      goal: 0.007
      trajectory: 0.1
    Actuator7:
      goal: 0.007
      trajectory: 0.1

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
