#velocity_joint_mode_controller:
#  type: joint_mode_controller/JointModeController
#  joint_mode: 2 # velocity

velocity_trajectory_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - Actuator1
    - Actuator2
    - Actuator3
    - Actuator4
    - Actuator5
    - Actuator6
    - Actuator7
  gains:
    Actuator1: {p: 6, d: 0.1, i: 0.5, i_clamp: 2.0}
    Actuator2: {p: 8, d: 0.1, i: 0.5, i_clamp: 2.0}
    Actuator3: {p: 6, d: 0.1, i: 0.5, i_clamp: 2.0}
    Actuator4: {p: 8, d: 0.1, i: 0.5, i_clamp: 2.0}
    Actuator5: {p: 8, d: 0.1, i: 0.5, i_clamp: 2.0}
    Actuator6: {p: 8, d: 0.2, i: 0.5, i_clamp: 2.0}
    Actuator7: {p: 8, d: 0.1, i: 0.5, i_clamp: 2.0}

  velocity_ff:
    Actuator1: 1.0
    Actuator2: 1.0
    Actuator3: 1.0
    Actuator4: 1.0
    Actuator5: 1.0
    Actuator6: 1.0
    Actuator7: 1.0

  constraints:
    stopped_velocity_tolerance: 0.01
    goal_time: 5.0
    Actuator1:
      goal: 0.01
      trajectory: 0.15
    Actuator2:
      goal: 0.01
      trajectory: 0.15
    Actuator3:
      goal: 0.01
      trajectory: 0.15
    Actuator4:
      goal: 0.01
      trajectory: 0.15
    Actuator5:
      goal: 0.01
      trajectory: 0.15
    Actuator6:
      goal: 0.01
      trajectory: 0.15
    Actuator7:
      goal: 0.01
      trajectory: 0.15

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
